### ISSUE TITLE
function you want to build in our App

### ISSUE THREAD

**Issue by yc0191** [Yapp-17th/Android_2_Client#2]
저번 회의때 본인이 해보고 싶은 앱의 기능이나 빌드에 대해서 간략하게 적어주시면 되겠습니다.
아이데이션과 관계없이 적어주시면 되구요.
추후 아이디어 빌드때 반영해서 생각할 수 하기 위함 입니다.

**Comment by Haemin-Park** [comment]
- 로그인 기능 있었으면 좋겠습니다.
- 만약 사용자끼리 상호작용하는 앱이라면 알림기능 넣어서 알림들 모아둔 알림탭 만들어보고 싶습니다.

**Comment by dev-donghwan** [comment]
https://developers.facebook.com/docs/instagram

활용한 인스타그램 관리 app
